name: laundry
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Peta dan lokasi
  flutter_map: ^7.0.0
  latlong2: ^0.9.0
  google_maps_flutter: ^2.5.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0

  #dropdown
  animated_custom_dropdown: 1.5.0

  # Icon bawaan iOS
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter untuk memastikan kualitas kode
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
